### PR TITLE
S3 test check

### PR DESCRIPTION
**Pull request by johannesboyne**
Checking to keep or remove the S3-test suite https://github.com/gaul/s3-tests

### CODE REVIEW

**Comment by johannesboyne** [comment]
```
FAILED (SKIP=55, errors=454, failures=23)
```

Let's see whether it makes sense to keep this inside the repository, or simply removing it. I have to dive into the errors but as there are so many, I assume it will just be a configuration issue right now.

**Comment by gaul** [comment]
s3-tests vastly improved S3Proxy compatibility so I recommend using it for gofakes3. However it is hard to work with the upstream project and I have maintained my fork for years.  Further they are porting to boto3 which seems to change everything and are not merging new pull requests to avoid conflicts.  You are welcome to use my fork but I periodically rewrite history when I track upstream changes.

**Comment by shabbyrobe** [comment]
> FAILED (SKIP=55, errors=454, failures=23)

Do any of them pass? :laughing:

@gaul, would you recommend we use your fork or the original repo?

**Comment by gaul** [comment]
I recommend creating a new fork of the original repo but using my fork as a reference since it shows how to disable failing tests via attributes.  There is nothing special about my fork and I hope that upstream merges all my pull requests some day.

**Pull request closed without merging**
